"""Create VLM training notebooks (00-05)."""

import json
from pathlib import Path

notebooks_dir = Path("ml-training/notebooks")

def make_nb(cells):
    return {
        "cells": cells,
        "metadata": {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"}},
        "nbformat": 4,
        "nbformat_minor": 5,
    }

def md(src): return {"cell_type": "markdown", "metadata": {}, "source": src}
def code(src): return {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": src}

# ══════════════════════════════════════════════════════════════
# Notebook 00: VLM Environment Setup
# ══════════════════════════════════════════════════════════════
nb00 = make_nb([
    md(["# 00 — VLM Environment Setup\n",
        "\n",
        "Sets up Google Colab/Vertex AI Workbench for Qwen3-VL fine-tuning.\n",
        "Installs Unsloth for efficient QLoRA training.\n"]),
    code([
        "# Cell 1: Install dependencies\n",
        "!pip install -q unsloth transformers accelerate bitsandbytes\n",
        "!pip install -q qwen-vl-utils pillow sentencepiece\n",
        "!pip install -q mlflow httpx pyyaml google-generativeai\n",
        "!pip install -q datasets evaluate scikit-learn\n",
    ]),
    code([
        "# Cell 2: Mount Google Drive\n",
        "from google.colab import drive\n",
        "drive.mount('/content/drive')\n",
        "\n",
        "from pathlib import Path\n",
        "\n",
        "# Project dirs on Drive\n",
        "PROJECT_DIR = Path('/content/drive/MyDrive/numera-ml')\n",
        "DATA_DIR = PROJECT_DIR / 'data'\n",
        "MODELS_DIR = PROJECT_DIR / 'models'\n",
        "LABELS_DIR = DATA_DIR / 'labels'\n",
        "PDFS_DIR = DATA_DIR / 'pdfs'\n",
        "IMAGES_DIR = DATA_DIR / 'page_images'\n",
        "\n",
        "for d in [DATA_DIR, MODELS_DIR, LABELS_DIR, PDFS_DIR, IMAGES_DIR]:\n",
        "    d.mkdir(parents=True, exist_ok=True)\n",
        "\n",
        "print('Project dirs ready ✅')\n",
    ]),
    code([
        "# Cell 3: Verify GPU\n",
        "import torch\n",
        "print(f'PyTorch: {torch.__version__}')\n",
        "print(f'CUDA available: {torch.cuda.is_available()}')\n",
        "if torch.cuda.is_available():\n",
        "    print(f'GPU: {torch.cuda.get_device_name()}')\n",
        "    print(f'VRAM: {torch.cuda.get_device_properties(0).total_mem / 1e9:.1f} GB')\n",
    ]),
])

# ══════════════════════════════════════════════════════════════
# Notebook 01: Auto-Labeling via Gemini Flash
# ══════════════════════════════════════════════════════════════
nb01 = make_nb([
    md(["# 01 — Auto-Labeling with Gemini 1.5 Flash\n",
        "\n",
        "Uses Gemini Flash API to automatically extract structured labels\n",
        "from financial document pages. These labels become training data\n",
        "for fine-tuning Qwen3-VL.\n",
        "\n",
        "**Cost**: ~₹500 for 1,150 PDFs (34,500 pages)\n"]),
    code([
        "# Cell 1: Configure Gemini API\n",
        "import google.generativeai as genai\n",
        "import os, json, time\n",
        "from pathlib import Path\n",
        "from PIL import Image\n",
        "\n",
        "# Set your API key (from Google AI Studio)\n",
        "GEMINI_API_KEY = os.environ.get('GEMINI_API_KEY', 'your-key-here')\n",
        "genai.configure(api_key=GEMINI_API_KEY)\n",
        "\n",
        "model = genai.GenerativeModel('gemini-1.5-flash')\n",
        "print('Gemini configured ✅')\n",
    ]),
    code([
        "# Cell 2: Labeling prompt\n",
        "LABELING_PROMPT = '''Analyze this financial statement page and extract ALL tables.\n",
        "\n",
        "For EACH table, provide:\n",
        "{\n",
        "  \"table_id\": \"page{page}_table{n}\",\n",
        "  \"zone_type\": \"BALANCE_SHEET|INCOME_STATEMENT|CASH_FLOW|NOTES_FIXED_ASSETS|NOTES_RECEIVABLES|NOTES_DEBT|NOTES_OTHER|OTHER\",\n",
        "  \"zone_label\": \"Human readable name\",\n",
        "  \"confidence\": 0.95,\n",
        "  \"periods\": [\"2025\", \"2024\"],\n",
        "  \"currency\": \"USD\",\n",
        "  \"unit\": \"millions\",\n",
        "  \"headers\": [\"Account\", \"2025\", \"2024\"],\n",
        "  \"rows\": [\n",
        "    {\"label\": \"Revenue\", \"values\": [12500, 11200], \"is_total\": false, \"indent_level\": 0}\n",
        "  ]\n",
        "}\n",
        "\n",
        "Return JSON: {\"page_number\": N, \"tables\": [...], \"page_type\": \"financial_statement|notes|cover|text_only\"}'''\n",
    ]),
    code([
        "# Cell 3: Process all page images\n",
        "import glob\n",
        "\n",
        "IMAGES_DIR = Path('/content/drive/MyDrive/numera-ml/data/page_images')\n",
        "LABELS_DIR = Path('/content/drive/MyDrive/numera-ml/data/labels')\n",
        "\n",
        "image_files = sorted(glob.glob(str(IMAGES_DIR / '**/*.png'), recursive=True))\n",
        "print(f'Found {len(image_files)} page images to label')\n",
        "\n",
        "errors = []\n",
        "for i, img_path in enumerate(image_files):\n",
        "    label_path = LABELS_DIR / Path(img_path).relative_to(IMAGES_DIR).with_suffix('.json')\n",
        "    if label_path.exists():\n",
        "        continue  # Already labeled\n",
        "\n",
        "    try:\n",
        "        img = Image.open(img_path)\n",
        "        response = model.generate_content(\n",
        "            [LABELING_PROMPT, img],\n",
        "            generation_config={'response_mime_type': 'application/json'}\n",
        "        )\n",
        "        label_data = json.loads(response.text)\n",
        "\n",
        "        label_path.parent.mkdir(parents=True, exist_ok=True)\n",
        "        label_path.write_text(json.dumps(label_data, indent=2))\n",
        "\n",
        "        if (i + 1) % 100 == 0:\n",
        "            print(f'Labeled {i+1}/{len(image_files)}')\n",
        "\n",
        "        time.sleep(0.5)  # Rate limit\n",
        "    except Exception as e:\n",
        "        errors.append((img_path, str(e)))\n",
        "        time.sleep(2)\n",
        "\n",
        "print(f'Done! Errors: {len(errors)}')\n",
    ]),
    code([
        "# Cell 4: Quality check — sample 20 labels\n",
        "import random\n",
        "\n",
        "label_files = sorted(glob.glob(str(LABELS_DIR / '**/*.json'), recursive=True))\n",
        "samples = random.sample(label_files, min(20, len(label_files)))\n",
        "\n",
        "for f in samples[:5]:\n",
        "    data = json.loads(Path(f).read_text())\n",
        "    tables = data.get('tables', [])\n",
        "    print(f'{Path(f).name}: {len(tables)} tables')\n",
        "    for t in tables:\n",
        "        print(f'  - {t.get(\"zone_type\")}: {len(t.get(\"rows\", []))} rows')\n",
    ]),
])

# ══════════════════════════════════════════════════════════════
# Notebook 02: Data Preparation
# ══════════════════════════════════════════════════════════════
nb02 = make_nb([
    md(["# 02 — Data Preparation for Qwen3-VL Fine-Tuning\n",
        "\n",
        "Converts Gemini auto-labels into conversation-format training data\n",
        "for Qwen3-VL QLoRA fine-tuning.\n"]),
    code([
        "# Cell 1: Load labels and build conversation pairs\n",
        "import json, glob, random\n",
        "from pathlib import Path\n",
        "\n",
        "LABELS_DIR = Path('/content/drive/MyDrive/numera-ml/data/labels')\n",
        "IMAGES_DIR = Path('/content/drive/MyDrive/numera-ml/data/page_images')\n",
        "OUTPUT_DIR = Path('/content/drive/MyDrive/numera-ml/data/training')\n",
        "OUTPUT_DIR.mkdir(parents=True, exist_ok=True)\n",
        "\n",
        "label_files = sorted(glob.glob(str(LABELS_DIR / '**/*.json'), recursive=True))\n",
        "print(f'Found {len(label_files)} labeled pages')\n",
        "\n",
        "# Build conversation-format training data\n",
        "conversations = []\n",
        "for lf in label_files:\n",
        "    label = json.loads(Path(lf).read_text())\n",
        "    img_path = str(IMAGES_DIR / Path(lf).relative_to(LABELS_DIR).with_suffix('.png'))\n",
        "\n",
        "    if not Path(img_path).exists():\n",
        "        continue\n",
        "\n",
        "    conversations.append({\n",
        "        'image': img_path,\n",
        "        'conversations': [\n",
        "            {'role': 'user', 'content': 'Extract all financial tables from this page with complete structure, zone classification, periods, currency, and values. Return JSON.'},\n",
        "            {'role': 'assistant', 'content': json.dumps(label)},\n",
        "        ]\n",
        "    })\n",
        "\n",
        "print(f'Built {len(conversations)} training conversations')\n",
    ]),
    code([
        "# Cell 2: Train/val/test split (80/10/10)\n",
        "random.shuffle(conversations)\n",
        "\n",
        "n = len(conversations)\n",
        "train = conversations[:int(n * 0.8)]\n",
        "val = conversations[int(n * 0.8):int(n * 0.9)]\n",
        "test = conversations[int(n * 0.9):]\n",
        "\n",
        "for name, data in [('train', train), ('val', val), ('test', test)]:\n",
        "    path = OUTPUT_DIR / f'{name}.json'\n",
        "    path.write_text(json.dumps(data, indent=2))\n",
        "    print(f'{name}: {len(data)} samples → {path.name}')\n",
    ]),
])

# ══════════════════════════════════════════════════════════════
# Notebook 03: Fine-Tuning with Unsloth
# ══════════════════════════════════════════════════════════════
nb03 = make_nb([
    md(["# 03 — Qwen3-VL-8B Fine-Tuning with Unsloth QLoRA\n",
        "\n",
        "Fine-tunes Qwen3-VL-8B on financial document extraction using\n",
        "QLoRA (4-bit quantized LoRA) for efficient training on T4/A100.\n",
        "\n",
        "**Estimated time**: ~4 hrs on A100, ~12 hrs on T4\n"]),
    code([
        "# Cell 1: Load model with Unsloth\n",
        "from unsloth import FastVisionModel\n",
        "import torch\n",
        "\n",
        "model, tokenizer = FastVisionModel.from_pretrained(\n",
        "    'Qwen/Qwen3-VL-8B-Instruct',\n",
        "    load_in_4bit=True,\n",
        "    use_gradient_checkpointing='unsloth',\n",
        ")\n",
        "\n",
        "# Add LoRA adapters\n",
        "model = FastVisionModel.get_peft_model(\n",
        "    model,\n",
        "    finetune_vision_layers=True,\n",
        "    finetune_language_layers=True,\n",
        "    finetune_attention_modules=True,\n",
        "    finetune_mlp_modules=True,\n",
        "    r=16,\n",
        "    lora_alpha=16,\n",
        "    lora_dropout=0,\n",
        "    bias='none',\n",
        "    random_state=42,\n",
        ")\n",
        "\n",
        "print(f'Trainable params: {model.print_trainable_parameters()}')\n",
    ]),
    code([
        "# Cell 2: Load training data\n",
        "import json\n",
        "from pathlib import Path\n",
        "from PIL import Image\n",
        "\n",
        "TRAINING_DIR = Path('/content/drive/MyDrive/numera-ml/data/training')\n",
        "train_data = json.loads((TRAINING_DIR / 'train.json').read_text())\n",
        "val_data = json.loads((TRAINING_DIR / 'val.json').read_text())\n",
        "\n",
        "print(f'Train: {len(train_data)}, Val: {len(val_data)}')\n",
        "\n",
        "# Convert to HuggingFace dataset format\n",
        "from datasets import Dataset\n",
        "\n",
        "def format_for_training(item):\n",
        "    img = Image.open(item['image']).convert('RGB')\n",
        "    user_msg = item['conversations'][0]['content']\n",
        "    assistant_msg = item['conversations'][1]['content']\n",
        "    return {\n",
        "        'image': img,\n",
        "        'instruction': user_msg,\n",
        "        'output': assistant_msg,\n",
        "    }\n",
        "\n",
        "train_dataset = Dataset.from_list([format_for_training(d) for d in train_data])\n",
        "val_dataset = Dataset.from_list([format_for_training(d) for d in val_data])\n",
        "print(f'Datasets ready: train={len(train_dataset)}, val={len(val_dataset)}')\n",
    ]),
    code([
        "# Cell 3: Train\n",
        "from transformers import TrainingArguments\n",
        "from trl import SFTTrainer\n",
        "import mlflow\n",
        "\n",
        "# Configure MLflow tracking\n",
        "mlflow.set_tracking_uri('file:///content/drive/MyDrive/numera-ml/mlruns')\n",
        "\n",
        "training_args = TrainingArguments(\n",
        "    output_dir='/content/drive/MyDrive/numera-ml/models/checkpoints/qwen3vl',\n",
        "    num_train_epochs=3,\n",
        "    per_device_train_batch_size=1,\n",
        "    gradient_accumulation_steps=8,\n",
        "    learning_rate=1e-4,\n",
        "    lr_scheduler_type='cosine',\n",
        "    warmup_ratio=0.1,\n",
        "    fp16=not torch.cuda.is_bf16_supported(),\n",
        "    bf16=torch.cuda.is_bf16_supported(),\n",
        "    logging_steps=10,\n",
        "    save_strategy='epoch',\n",
        "    eval_strategy='epoch',\n",
        "    save_total_limit=3,\n",
        "    optim='adamw_8bit',\n",
        "    seed=42,\n",
        "    report_to='mlflow',\n",
        ")\n",
        "\n",
        "with mlflow.start_run(run_name='qwen3vl-financial-finetune'):\n",
        "    mlflow.log_params({\n",
        "        'model': 'Qwen3-VL-8B-Instruct',\n",
        "        'method': 'QLoRA',\n",
        "        'lora_r': 16,\n",
        "        'train_samples': len(train_dataset),\n",
        "        'val_samples': len(val_dataset),\n",
        "    })\n",
        "\n",
        "    trainer = SFTTrainer(\n",
        "        model=model,\n",
        "        tokenizer=tokenizer,\n",
        "        train_dataset=train_dataset,\n",
        "        eval_dataset=val_dataset,\n",
        "        args=training_args,\n",
        "        max_seq_length=2048,\n",
        "    )\n",
        "\n",
        "    trainer.train()\n",
        "    print('Training complete! ✅')\n",
    ]),
    code([
        "# Cell 4: Save LoRA adapters\n",
        "ADAPTER_DIR = '/content/drive/MyDrive/numera-ml/models/qwen3vl-financial-lora'\n",
        "model.save_pretrained(ADAPTER_DIR)\n",
        "tokenizer.save_pretrained(ADAPTER_DIR)\n",
        "print(f'LoRA adapters saved to {ADAPTER_DIR}')\n",
    ]),
])

# ══════════════════════════════════════════════════════════════
# Notebook 04: Evaluation
# ══════════════════════════════════════════════════════════════
nb04 = make_nb([
    md(["# 04 — Model Evaluation\n",
        "\n",
        "Evaluates the fine-tuned Qwen3-VL on the test set.\n",
        "\n",
        "**Targets**: ≥98% cell accuracy, ≥95% TEDS, ≥98% zone accuracy\n"]),
    code([
        "# Cell 1: Load fine-tuned model\n",
        "from unsloth import FastVisionModel\n",
        "\n",
        "model, tokenizer = FastVisionModel.from_pretrained(\n",
        "    '/content/drive/MyDrive/numera-ml/models/qwen3vl-financial-lora',\n",
        "    load_in_4bit=True,\n",
        ")\n",
        "FastVisionModel.for_inference(model)\n",
        "print('Model loaded for evaluation')\n",
    ]),
    code([
        "# Cell 2: Run evaluation on test set\n",
        "import json\n",
        "from pathlib import Path\n",
        "from PIL import Image\n",
        "\n",
        "test_data = json.loads(Path('/content/drive/MyDrive/numera-ml/data/training/test.json').read_text())\n",
        "print(f'Evaluating on {len(test_data)} test samples')\n",
        "\n",
        "results = []\n",
        "for item in test_data:\n",
        "    img = Image.open(item['image']).convert('RGB')\n",
        "    expected = json.loads(item['conversations'][1]['content'])\n",
        "\n",
        "    # Run inference\n",
        "    messages = [\n",
        "        {'role': 'user', 'content': [{'type': 'image', 'image': img}, {'type': 'text', 'text': item['conversations'][0]['content']}]}\n",
        "    ]\n",
        "    prompt = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)\n",
        "    inputs = tokenizer(prompt, images=[img], return_tensors='pt').to('cuda')\n",
        "\n",
        "    import torch\n",
        "    with torch.no_grad():\n",
        "        output = model.generate(**inputs, max_new_tokens=4096, do_sample=False)\n",
        "    predicted_text = tokenizer.decode(output[0][inputs['input_ids'].shape[1]:], skip_special_tokens=True)\n",
        "\n",
        "    try:\n",
        "        predicted = json.loads(predicted_text)\n",
        "    except json.JSONDecodeError:\n",
        "        predicted = {'tables': []}\n",
        "\n",
        "    results.append({'expected': expected, 'predicted': predicted, 'image': item['image']})\n",
        "\n",
        "print(f'Evaluation complete: {len(results)} samples')\n",
    ]),
    code([
        "# Cell 3: Calculate metrics\n",
        "\n",
        "zone_correct = 0\n",
        "zone_total = 0\n",
        "value_correct = 0\n",
        "value_total = 0\n",
        "\n",
        "for r in results:\n",
        "    exp_tables = r['expected'].get('tables', [])\n",
        "    pred_tables = r['predicted'].get('tables', [])\n",
        "\n",
        "    for exp, pred in zip(exp_tables, pred_tables):\n",
        "        # Zone accuracy\n",
        "        zone_total += 1\n",
        "        if exp.get('zone_type') == pred.get('zone_type'):\n",
        "            zone_correct += 1\n",
        "\n",
        "        # Value accuracy (cell-level)\n",
        "        for exp_row, pred_row in zip(exp.get('rows', []), pred.get('rows', [])):\n",
        "            for exp_val, pred_val in zip(exp_row.get('values', []), pred_row.get('values', [])):\n",
        "                value_total += 1\n",
        "                if exp_val == pred_val:\n",
        "                    value_correct += 1\n",
        "\n",
        "zone_acc = zone_correct / zone_total if zone_total else 0\n",
        "cell_acc = value_correct / value_total if value_total else 0\n",
        "\n",
        "print(f'Zone accuracy: {zone_acc:.2%} (target: ≥98%)')\n",
        "print(f'Cell accuracy: {cell_acc:.2%} (target: ≥98%)')\n",
        "print(f'Zone: {zone_correct}/{zone_total}, Cell: {value_correct}/{value_total}')\n",
        "\n",
        "import mlflow\n",
        "mlflow.log_metrics({'zone_accuracy': zone_acc, 'cell_accuracy': cell_acc})\n",
    ]),
])

# ══════════════════════════════════════════════════════════════
# Notebook 05: Export to MLflow / Production
# ══════════════════════════════════════════════════════════════
nb05 = make_nb([
    md(["# 05 — Export Fine-Tuned Model\n",
        "\n",
        "Merges LoRA adapters into full model, quantizes for deployment,\n",
        "and registers in MLflow for production use.\n"]),
    code([
        "# Cell 1: Merge LoRA → full model\n",
        "from unsloth import FastVisionModel\n",
        "\n",
        "model, tokenizer = FastVisionModel.from_pretrained(\n",
        "    '/content/drive/MyDrive/numera-ml/models/qwen3vl-financial-lora',\n",
        "    load_in_4bit=True,\n",
        ")\n",
        "\n",
        "EXPORT_DIR = '/content/drive/MyDrive/numera-ml/models/qwen3vl-financial-merged'\n",
        "model.save_pretrained_merged(EXPORT_DIR, tokenizer, save_method='merged_16bit')\n",
        "print(f'Merged model saved to {EXPORT_DIR}')\n",
    ]),
    code([
        "# Cell 2: Quantize for deployment (4-bit GGUF)\n",
        "# This creates a compact model for CPU/small GPU inference\n",
        "GGUF_DIR = '/content/drive/MyDrive/numera-ml/models/qwen3vl-financial-gguf'\n",
        "model.save_pretrained_gguf(\n",
        "    GGUF_DIR, tokenizer,\n",
        "    quantization_method='q4_k_m',\n",
        ")\n",
        "print(f'Quantized GGUF model saved to {GGUF_DIR}')\n",
    ]),
    code([
        "# Cell 3: Register in MLflow\n",
        "import mlflow\n",
        "\n",
        "mlflow.set_tracking_uri('file:///content/drive/MyDrive/numera-ml/mlruns')\n",
        "\n",
        "with mlflow.start_run(run_name='qwen3vl-export'):\n",
        "    mlflow.log_artifact(EXPORT_DIR, 'model')\n",
        "    result = mlflow.register_model(\n",
        "        f'runs:/{mlflow.active_run().info.run_id}/model',\n",
        "        'qwen3vl-financial'\n",
        "    )\n",
        "\n",
        "    from mlflow.tracking import MlflowClient\n",
        "    client = MlflowClient()\n",
        "    client.transition_model_version_stage(\n",
        "        name='qwen3vl-financial',\n",
        "        version=result.version,\n",
        "        stage='Production',\n",
        "    )\n",
        "\n",
        "print(f'Model registered as qwen3vl-financial v{result.version} → Production')\n",
        "print('Set OCR_VLM_MODEL_PATH to the exported model dir in your docker-compose.yml')\n",
    ]),
])

# Write all notebooks
for name, nb in [
    ("00_vlm_environment_setup.ipynb", nb00),
    ("01_vlm_auto_labeling.ipynb", nb01),
    ("02_vlm_data_preparation.ipynb", nb02),
    ("03_vlm_fine_tuning.ipynb", nb03),
    ("04_vlm_evaluation.ipynb", nb04),
    ("05_vlm_export.ipynb", nb05),
]:
    with open(notebooks_dir / name, "w", encoding="utf-8") as f:
        json.dump(nb, f, indent=2)
    print(f"Created {name}")
