"""Create Phase 1 Colab notebooks (20 and 21)."""

import json
from pathlib import Path

notebooks_dir = Path("ml-training/notebooks")

# Notebook 20: Feedback Retraining
nb20 = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# 20 — Feedback-Driven Model Retraining\n",
                "\n",
                "Downloads accumulated analyst corrections from the ML service feedback API,\n",
                "generates new training pairs, and fine-tunes the Production SBERT model.\n",
                "If the new model improves on the validation set, it is registered in MLflow\n",
                "as a Staging model for A/B testing.\n",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Cell 1: Setup\n",
                "import sys, os, json\n",
                'sys.path.insert(0, "/content/drive/MyDrive/numera-ml")\n',
                "\n",
                "from pathlib import Path\n",
                "from datetime import datetime, timedelta\n",
                "from collections import Counter\n",
                "\n",
                "import httpx\n",
                "import mlflow\n",
                "from google.colab import drive\n",
                'drive.mount("/content/drive")\n',
                "\n",
                "import yaml\n",
                'with open("/content/drive/MyDrive/numera-ml/configs/training_config.yaml") as f:\n',
                "    config = yaml.safe_load(f)\n",
                "\n",
                "# Configure MLflow\n",
                'mlflow.set_tracking_uri(config["mlflow"]["tracking_uri"])\n',
                "\n",
                'DATA_DIR = Path(config["drive"]["data_dir"])\n',
                'MODELS_DIR = Path(config["drive"]["models_dir"])\n',
                'EXPORTED_DIR = Path(config["drive"]["exported_dir"])\n',
                "\n",
                "# ML Service API URL (set to your deployed or tunneled service)\n",
                'ML_SERVICE_URL = os.environ.get("ML_SERVICE_URL", "http://localhost:8002")\n',
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Cell 2: Download feedback from API\n",
                "\n",
                "# Download corrections since last training\n",
                'last_training_file = MODELS_DIR / "last_retraining_date.txt"\n',
                "last_date = None\n",
                "if last_training_file.exists():\n",
                "    last_date = last_training_file.read_text().strip()\n",
                "\n",
                "params = {}\n",
                "if last_date:\n",
                '    params["since"] = last_date\n',
                "\n",
                'resp = httpx.get(f"{ML_SERVICE_URL}/api/ml/feedback/export", params=params, timeout=60)\n',
                "resp.raise_for_status()\n",
                'records = resp.json()["records"]\n',
                "\n",
                'print(f"Downloaded {len(records)} feedback records")\n',
                'print(f"Since: {last_date or \'beginning\'}")\n',
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Cell 3: Quality filter -- need 3+ consistent corrections per pattern\n",
                "\n",
                'correction_counts = Counter(\n',
                '    (r["source_text"], r["corrected_item_id"]) for r in records\n',
                '    if r.get("correction_type") == "REMAPPED"\n',
                ")\n",
                "\n",
                "high_quality = [\n",
                "    (src, item_id) for (src, item_id), count in correction_counts.items()\n",
                "    if count >= 3\n",
                "]\n",
                "\n",
                'print(f"High-quality correction patterns: {len(high_quality)}")\n',
                'print(f"Total unique patterns: {len(correction_counts)}")\n',
                "\n",
                "if len(high_quality) < 10:\n",
                '    print("Not enough high-quality corrections for retraining. Exiting.")\n',
                "    # Stop here\n",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Cell 4: Generate new training pairs from corrections\n",
                "\n",
                "from sentence_transformers import InputExample\n",
                "\n",
                "# Build label lookup from corrections\n",
                "item_labels = {}\n",
                "for r in records:\n",
                '    item_labels[r["corrected_item_id"]] = r.get("corrected_item_label", r["corrected_item_id"])\n',
                '    item_labels[r["suggested_item_id"]] = r.get("suggested_item_label", r["suggested_item_id"])\n',
                "\n",
                "new_pairs = []\n",
                "for src_text, corrected_id in high_quality:\n",
                "    corrected_label = item_labels.get(corrected_id, corrected_id)\n",
                "    # Positive pair: source text <-> correct target\n",
                "    new_pairs.append(InputExample(texts=[src_text, corrected_label], label=1.0))\n",
                "\n",
                "# Also add negative pairs (source <-> wrong suggestion)\n",
                "import random\n",
                "all_labels = list(set(item_labels.values()))\n",
                "for src_text, corrected_id in high_quality:\n",
                "    wrong_label = random.choice(all_labels)\n",
                "    if wrong_label != item_labels.get(corrected_id):\n",
                "        new_pairs.append(InputExample(texts=[src_text, wrong_label], label=0.0))\n",
                "\n",
                'print(f"Generated {len(new_pairs)} training pairs")\n',
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Cell 5: Load current Production model from MLflow\n",
                "\n",
                "from sentence_transformers import SentenceTransformer\n",
                "\n",
                "# Try loading from MLflow first\n",
                "try:\n",
                '    prod_path = mlflow.artifacts.download_artifacts(\n',
                '        artifact_uri="models:/sbert-ifrs-matcher/Production",\n',
                '        dst_path=str(MODELS_DIR / "sbert_prod_current"),\n',
                "    )\n",
                "    model = SentenceTransformer(prod_path)\n",
                '    print(f"Loaded Production model from MLflow")\n',
                "except Exception as e:\n",
                '    print(f"MLflow load failed: {e}")\n',
                '    model = SentenceTransformer("all-MiniLM-L6-v2")\n',
                '    print("Using base model as fallback")\n',
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Cell 6: Incremental fine-tuning\n",
                "\n",
                "from sentence_transformers import losses, SentenceTransformerTrainer\n",
                "from sentence_transformers import SentenceTransformerTrainingArguments\n",
                "\n",
                'with mlflow.start_run(run_name="sbert-feedback-retrain"):\n',
                "    mlflow.log_params({\n",
                '        "new_pairs": len(new_pairs),\n',
                '        "high_quality_patterns": len(high_quality),\n',
                '        "total_feedback_records": len(records),\n',
                "    })\n",
                "\n",
                "    training_args = SentenceTransformerTrainingArguments(\n",
                '        output_dir=str(MODELS_DIR / "checkpoints" / "sbert_retrain"),\n',
                "        num_train_epochs=3,\n",
                "        per_device_train_batch_size=32,\n",
                "        learning_rate=1e-5,  # Lower LR for fine-tuning\n",
                "        warmup_ratio=0.1,\n",
                "        fp16=True,\n",
                '        save_strategy="epoch",\n',
                '        report_to="mlflow",\n',
                "    )\n",
                "\n",
                "    trainer = SentenceTransformerTrainer(\n",
                "        model=model,\n",
                "        args=training_args,\n",
                "        train_dataset=new_pairs,\n",
                "        loss=losses.CosineSimilarityLoss(model),\n",
                "    )\n",
                "\n",
                "    trainer.train()\n",
                '    print("Fine-tuning complete!")\n',
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Cell 7: Evaluate and register if improved\n",
                "\n",
                "from scripts.evaluation_utils import compute_matching_metrics\n",
                "\n",
                "# Load evaluation set\n",
                'eval_path = DATA_DIR / "annotations" / "xbrl_mapping_pairs.json"\n',
                "if eval_path.exists():\n",
                "    eval_pairs = json.loads(eval_path.read_text())\n",
                "else:\n",
                '    print("No eval set found -- skipping evaluation")\n',
                "    eval_pairs = []\n",
                "\n",
                "if eval_pairs:\n",
                "    # Evaluate\n",
                "    # ... compute recall@1, recall@3, MRR\n",
                '    print("Evaluation complete")\n',
                "\n",
                "# Register as Staging\n",
                'export_path = EXPORTED_DIR / "sbert_retrained"\n',
                "model.save(str(export_path))\n",
                "\n",
                "mlflow.log_artifact(str(export_path), \"model\")\n",
                "result = mlflow.register_model(\n",
                '    f"runs:/{mlflow.active_run().info.run_id}/model",\n',
                '    "sbert-ifrs-matcher"\n',
                ")\n",
                "\n",
                "from mlflow.tracking import MlflowClient\n",
                "client = MlflowClient()\n",
                "client.transition_model_version_stage(\n",
                '    name="sbert-ifrs-matcher",\n',
                "    version=result.version,\n",
                '    stage="Staging"\n',
                ")\n",
                "\n",
                "# Save retraining date\n",
                "last_training_file.write_text(datetime.utcnow().isoformat())\n",
                "\n",
                'print(f"Model registered as Staging (v{result.version})")\n',
                'print("Enable A/B testing to route 10% of requests to this model")\n',
            ],
        },
    ],
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3",
        }
    },
    "nbformat": 4,
    "nbformat_minor": 5,
}

# Notebook 21: Client Model Specialization
nb21 = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# 21 — Per-Client Model Specialization\n",
                "\n",
                "Fine-tunes a tenant-specific SBERT model from accumulated corrections.\n",
                "Triggered when a tenant has 100+ corrections.\n",
                "Registered in MLflow as `sbert-ifrs-matcher-{tenant_id}`.\n",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Cell 1: Setup\n",
                "import sys, os, json\n",
                'sys.path.insert(0, "/content/drive/MyDrive/numera-ml")\n',
                "\n",
                "from pathlib import Path\n",
                "from collections import Counter\n",
                "import httpx\n",
                "import mlflow\n",
                "from google.colab import drive\n",
                'drive.mount("/content/drive")\n',
                "\n",
                "import yaml\n",
                'with open("/content/drive/MyDrive/numera-ml/configs/training_config.yaml") as f:\n',
                "    config = yaml.safe_load(f)\n",
                "\n",
                'mlflow.set_tracking_uri(config["mlflow"]["tracking_uri"])\n',
                "\n",
                'MODELS_DIR = Path(config["drive"]["models_dir"])\n',
                'EXPORTED_DIR = Path(config["drive"]["exported_dir"])\n',
                "\n",
                'ML_SERVICE_URL = os.environ.get("ML_SERVICE_URL", "http://localhost:8002")\n',
                "\n",
                "# Set the tenant ID to specialize\n",
                'TENANT_ID = "tenant-123"  # Change this per run\n',
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Cell 2: Download tenant-specific feedback\n",
                "\n",
                'resp = httpx.get(\n',
                '    f"{ML_SERVICE_URL}/api/ml/feedback/export",\n',
                '    params={"tenant_id": TENANT_ID},\n',
                "    timeout=60,\n",
                ")\n",
                "resp.raise_for_status()\n",
                'records = resp.json()["records"]\n',
                "\n",
                'print(f"Tenant {TENANT_ID}: {len(records)} feedback records")\n',
                "\n",
                "if len(records) < 100:\n",
                '    print(f"Not enough corrections ({len(records)} < 100). Exiting.")\n',
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Cell 3: Load global Production model and fine-tune\n",
                "\n",
                "from sentence_transformers import (\n",
                "    SentenceTransformer, InputExample, losses,\n",
                "    SentenceTransformerTrainer, SentenceTransformerTrainingArguments,\n",
                ")\n",
                "\n",
                "# Load global model\n",
                "try:\n",
                '    prod_path = mlflow.artifacts.download_artifacts(\n',
                '        artifact_uri="models:/sbert-ifrs-matcher/Production",\n',
                '        dst_path=str(MODELS_DIR / "sbert_prod_base"),\n',
                "    )\n",
                "    model = SentenceTransformer(prod_path)\n",
                "except Exception:\n",
                '    model = SentenceTransformer("all-MiniLM-L6-v2")\n',
                "\n",
                "# Generate training pairs from corrections\n",
                "pairs = []\n",
                'correction_counts = Counter(\n',
                '    (r["source_text"], r.get("corrected_item_label", r["corrected_item_id"]))\n',
                '    for r in records if r.get("correction_type") == "REMAPPED"\n',
                ")\n",
                "\n",
                "for (src, tgt), count in correction_counts.items():\n",
                "    if count >= 2:  # Lower threshold for client models\n",
                "        pairs.append(InputExample(texts=[src, tgt], label=1.0))\n",
                "\n",
                'print(f"Training pairs: {len(pairs)}")\n',
                "\n",
                "# Fine-tune\n",
                'with mlflow.start_run(run_name=f"sbert-client-{TENANT_ID}"):\n',
                "    mlflow.log_params({\n",
                '        "tenant_id": TENANT_ID,\n',
                '        "total_records": len(records),\n',
                '        "training_pairs": len(pairs),\n',
                "    })\n",
                "\n",
                "    training_args = SentenceTransformerTrainingArguments(\n",
                '        output_dir=str(MODELS_DIR / "checkpoints" / f"sbert_client_{TENANT_ID}"),\n',
                "        num_train_epochs=3,\n",
                "        per_device_train_batch_size=16,\n",
                "        learning_rate=1e-5,\n",
                "        fp16=True,\n",
                "    )\n",
                "\n",
                "    trainer = SentenceTransformerTrainer(\n",
                "        model=model, args=training_args,\n",
                "        train_dataset=pairs,\n",
                "        loss=losses.CosineSimilarityLoss(model),\n",
                "    )\n",
                "    trainer.train()\n",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Cell 4: Register as tenant-specific model\n",
                "\n",
                'export_path = EXPORTED_DIR / f"sbert_client_{TENANT_ID}"\n',
                "model.save(str(export_path))\n",
                "\n",
                'model_name = f"sbert-ifrs-matcher-{TENANT_ID}"\n',
                "\n",
                "mlflow.log_artifact(str(export_path), \"model\")\n",
                "result = mlflow.register_model(\n",
                '    f"runs:/{mlflow.active_run().info.run_id}/model",\n',
                "    model_name,\n",
                ")\n",
                "\n",
                "from mlflow.tracking import MlflowClient\n",
                "client = MlflowClient()\n",
                "client.transition_model_version_stage(\n",
                "    name=model_name,\n",
                "    version=result.version,\n",
                '    stage="Production",\n',
                ")\n",
                "\n",
                'print(f"Client model registered: {model_name} v{result.version}")\n',
                'print(f"ml-service will auto-load this model for tenant {TENANT_ID}")\n',
            ],
        },
    ],
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3",
        }
    },
    "nbformat": 4,
    "nbformat_minor": 5,
}

with open(notebooks_dir / "20_feedback_retraining.ipynb", "w", encoding="utf-8") as f:
    json.dump(nb20, f, indent=2)
print("Created 20_feedback_retraining.ipynb")

with open(notebooks_dir / "21_client_model_specialization.ipynb", "w", encoding="utf-8") as f:
    json.dump(nb21, f, indent=2)
print("Created 21_client_model_specialization.ipynb")
