package com.numera.shared.pdf

import com.openhtmltopdf.pdfboxout.PdfRendererBuilder
import org.slf4j.LoggerFactory
import org.springframework.core.io.ByteArrayResource
import org.springframework.stereotype.Service
import java.io.ByteArrayOutputStream
import java.time.LocalDate
import java.time.format.DateTimeFormatter

/**
 * Enterprise PDF generation service using OpenHTML-to-PDF.
 * Supports header/footer with page numbers, company logo, and date.
 */
@Service
class PdfGenerator {
    private val log = LoggerFactory.getLogger(javaClass)

    data class PdfOptions(
        val title: String? = null,
        val cssTemplate: String? = null,
        val showHeader: Boolean = true,
        val showFooter: Boolean = true,
        val companyName: String = "Numera",
        val logoBase64: String? = null,
    )

    fun renderHtml(htmlContent: String, title: String? = null): ByteArray {
        return renderHtml(htmlContent, PdfOptions(title = title))
    }

    fun renderHtml(htmlContent: String, options: PdfOptions): ByteArray {
        val normalizedHtml = normalizeHtml(htmlContent, options)
        val output = ByteArrayOutputStream()

        runCatching {
            PdfRendererBuilder()
                .useFastMode()
                .withHtmlContent(normalizedHtml, null)
                .toStream(output)
                .run()
        }.onFailure { ex ->
            log.error("Failed to render PDF from HTML", ex)
            throw IllegalStateException("Unable to generate PDF", ex)
        }

        return output.toByteArray()
    }

    fun renderHtmlAsResource(htmlContent: String, options: PdfOptions = PdfOptions()): ByteArrayResource {
        val bytes = renderHtml(htmlContent, options)
        return ByteArrayResource(bytes)
    }

    private fun normalizeHtml(htmlContent: String, options: PdfOptions): String {
        val trimmed = htmlContent.trim()
        val safeTitle = escapeHtml(options.title ?: "Document")
        val date = LocalDate.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd"))
        val cssBlock = options.cssTemplate ?: defaultCss()
        val headerBlock = if (options.showHeader) buildHeader(options.companyName, safeTitle, date, options.logoBase64) else ""
        val footerBlock = if (options.showFooter) buildFooter() else ""

        // If the content already contains a full HTML document, inject header/footer around the body content
        if (trimmed.contains("<html", ignoreCase = true)) {
            return trimmed
        }

        return """
            <!DOCTYPE html>
            <html>
              <head>
                <meta charset="UTF-8" />
                <title>$safeTitle</title>
                <style>
                  $cssBlock
                </style>
              </head>
              <body>
                $headerBlock
                <div class="content">$trimmed</div>
                $footerBlock
              </body>
            </html>
        """.trimIndent()
    }

    private fun buildHeader(companyName: String, title: String, date: String, logoBase64: String?): String {
        val logoHtml = if (logoBase64 != null) {
            """<img src="data:image/png;base64,$logoBase64" style="height:28px;margin-right:12px;" alt="Logo" />"""
        } else ""
        return """
            <div class="pdf-header">
              <div class="header-left">$logoHtml<span class="company-name">${escapeHtml(companyName)}</span></div>
              <div class="header-right">$title &mdash; $date</div>
            </div>
            <hr class="header-rule" />
        """.trimIndent()
    }

    private fun buildFooter(): String = """
        <div class="pdf-footer">
          <hr class="footer-rule" />
          <div class="footer-text">Confidential &mdash; Generated by Numera</div>
        </div>
    """.trimIndent()

    private fun defaultCss(): String = """
        @page {
            size: A4;
            margin: 20mm 15mm 20mm 15mm;
        }
        body {
            font-family: Helvetica, Arial, sans-serif;
            font-size: 10pt;
            line-height: 1.5;
            color: #111827;
            margin: 0;
            padding: 0;
        }
        .pdf-header {
            display: block;
            overflow: hidden;
            margin-bottom: 4px;
        }
        .header-left { float: left; font-size: 12pt; font-weight: 700; }
        .header-right { float: right; font-size: 9pt; color: #6b7280; }
        .company-name { vertical-align: middle; }
        .header-rule { border: none; border-top: 2px solid #2563eb; margin-bottom: 16px; }
        .footer-rule { border: none; border-top: 1px solid #d1d5db; margin-top: 24px; }
        .pdf-footer { margin-top: auto; }
        .footer-text { font-size: 8pt; color: #9ca3af; text-align: center; padding-top: 4px; }
        .content { margin: 0; }
        p { margin: 0 0 10px 0; }
        strong { font-weight: 700; }
        table { border-collapse: collapse; width: 100%; margin-bottom: 12px; }
        th, td { border: 1px solid #d1d5db; padding: 6px 8px; font-size: 9pt; text-align: left; }
        th { background-color: #f3f4f6; font-weight: 600; }
        h1 { font-size: 16pt; margin: 0 0 12px 0; }
        h2 { font-size: 13pt; margin: 16px 0 8px 0; }
        h3 { font-size: 11pt; margin: 12px 0 6px 0; }
    """.trimIndent()

    private fun escapeHtml(value: String): String = value
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
}